[units]          
angle = 'deg'        # Units used for angles
length = 'mm'        # units used for lengths

[panel]              # Panel parameters
number = 12          # number of panels in  the arena
omitted = []         # list  of omitted panels
offset_angle = 0     # offset angle for panel position
width = 40.5         # width of panels 
depth = 15           # depth from front to back of panels 

[pins]               # Header pin parameters
number = 15          # number of header pins
pitch = 2.54         # pitch (distance) between header pins
depth = 13.1         # depth from front to header pins 
omitted = []         # pins omitted from header

[pcb]
size_x = 228.6       # PCB size in x-dimension
size_y = 228.6       # PCB size in y-dimension
center_x = 177.8     # PCB center x-coordinate
center_y = 177.8     # PCB center y-coordinate 
line_width = 0.3     # PCB edge line width
cutout_diam = 157.0  # Inside hole radius
add_boundary = false # Add PCB boundary 
add_cutout = false   # Add PCB internal cutout

[pcb.panel]
ref_prefix = 'P'     # Symbol prefix for panel headers
ref_start = 1        # Start number for panel headers

[pcb.relative]
model = 1            # Model for relative component placement

# Lists of relative components for placement 
1   =  ['C1','C35','C36','C37','C38','C39','C40','U39','U40','U41','U42','U43','U44','R163','R164','R165','R166','R167','R168','R169','R170','R171','R172','R173','R174']               
2   =  ['C2','C41','C42','C43','C44','C45','C46','U45','U46','U47','U48','U49','U50','R175','R176','R177','R178','R179','R180','R181','R182','R183','R184','R185','R186']               
3   =  ['C3','C47','C48','C49','C50','C51','C52','U51','U52','U53','U54','U55','U56','R187','R188','R189','R190','R191','R192','R193','R194','R195','R196','R197','R198']               
4   =  ['C4','C53','C54','C55','C56','C57','C58','U57','U58','U59','U60','U61','U62','R199','R200','R201','R202','R203','R204','R205','R206','R207','R208','R209','R210']               
5   =  ['C5','C59','C60','C61','C62','C63','C64','U63','U64','U65','U66','U67','U68','R211','R212','R213','R214','R215','R216','R217','R218','R219','R220','R221','R222']               
6   =  ['C6','C65','C66','C67','C68','C69','C70','U69','U70','U71','U72','U73','U74','R223','R224','R225','R226','R227','R228','R229','R230','R231','R232','R233','R234']               
7   =  ['C7','C71','C72','C73','C74','C75','C76','U75','U76','U77','U78','U79','U80','R235','R236','R237','R238','R239','R240','R241','R242','R243','R244','R245','R246']               
8   =  ['C8','C77','C78','C79','C80','C81','C82','U81','U82','U83','U84','U85','U86','R247','R248','R249','R250','R251','R252','R253','R254','R255','R256','R257','R258']               
9   =  ['C9','C83','C84','C85','C86','C87','C88','U87','U88','U89','U90','U91','U92','R259','R260','R261','R262','R263','R264','R265','R266','R267','R268','R269','R270']               
10  =  ['C10','C89','C90','C91','C92','C93','C94','U93','U94','U95','U96','U97','U98','R271','R272','R273','R274','R275','R276','R277','R278','R279','R280','R281','R282']               
11  =  ['C11','C95','C96','C97','C98','C99','C100','U99','U100','U101','U102','U103','U104','R283','R284','R285','R286','R287','R288','R289','R290','R291','R292','R293','R294']             
12  =  ['C12','C101','C102','C103','C104','C105','C106','U105','U106','U107','U108','U109','U110','R295','R296','R297','R298','R299','R300','R301','R302','R303','R304','R305','R306']             









